name: clang-format Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Find common ancestor
      env:
        BASE_BRANCH: ${{ github.base_ref }}
      run: git merge-base --fork-point origin/$BASE_BRANCH
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: DanielWielanek/clang-format-action@main
      with:
        clang-format-version: '13'
        check-path: '.'
        files-list: ${{ steps.files.outputs.added_modified }}
        upstream-path: https://github.com/star-bnl/star-sw.git
