name: clang-format Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - id: files
    - uses: jitterbit/get-changed-files@v1
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: DanielWielanek/clang-format-action@main
      with:
        clang-format-version: '13'
        check-path: '.'
        files-list: ${{steps.files.outputs.al}}
        upstream-path: https://github.com/star-bnl/star-sw.git
