name: clang-format Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - name: Run clang-format style check for C/C++ files.
      uses: DanielWielanek/clang-format-action@main
      with:
        clang-format-version: '13'
        check-path: '.'
        upstream-branch: upstream/main
        upstream-path: https://github.com/star-bnl/star-sw.git
