name: clang-format Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - name: test_Files
      uses: actions/checkout@v3
      with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      # Example 1
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v34

    - name: List all changed files
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file was changed"
        done
        
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: DanielWielanek/clang-format-action@main
      with:
        clang-format-version: '13'
        check-path: '.'
        files-list: ${{ steps.files.outputs.added_modified }}
        upstream-path: https://github.com/star-bnl/star-sw.git
